manager:
  cmd: /bin/cluster-api-controller-manager
  image:
    tag: v4.20
    url: registry.redhat.io/openshift4/ose-cluster-api-rhel9
webhook:
  image:
    tag: latest
    url: quay.io/mveber/mce-capi-webhook-config
